# Generated by Django 4.2.4 on 2025-05-08 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('idMedicion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('nitrogeno', models.FloatField(blank=True, null=True)),
                ('fosforo', models.FloatField(blank=True, null=True)),
                ('potasio', models.FloatField(blank=True, null=True)),
                ('ph', models.FloatField(blank=True, null=True)),
                ('humedad', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'medicion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='postMediciones',
            fields=[
                ('idMedicion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('nitrogeno', models.FloatField(blank=True, null=True)),
                ('fosforo', models.FloatField(blank=True, null=True)),
                ('potasio', models.FloatField(blank=True, null=True)),
                ('ph', models.FloatField(blank=True, null=True)),
                ('humedad', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'medicion',
                'managed': False,
            },
        ),
    ]
