# Generated by Django 4.2.4 on 2025-05-12 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TerraSmart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicion',
            options={},
        ),
    ]
