# Generated by Django 4.2.4 on 2025-05-13 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TerraSmart', '0002_alter_medicion_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicion',
            options={'managed': False},
        ),
    ]
